#database connection
#eras(energy consumption)
#get 15 random airports(function)
#get all goals(function)
#create a new game(function)
#getting airport info(function)
#checking goals(function)
#calculate distance(function)
#airports in range(function)
#update game(function)
#game state(function)
